import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
async function main (): Promise<void> {
  // await prisma.countries.create({
  //   data: {
  //     countryID: 'CL',
  //     name: 'Chile'
  //   }
  // })
  // await prisma.regions.createMany({
  //   data: [
  //     {
  //       regionID: '1',
  //       romanNumber: 'I',
  //       name: 'Tarapacá',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '2',
  //       romanNumber: 'II',
  //       name: 'Antofagasta',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '3',
  //       romanNumber: 'III',
  //       name: 'Atacama',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '4',
  //       romanNumber: 'IV',
  //       name: 'Coquimbo',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '5',
  //       romanNumber: 'V',
  //       name: 'Valparaíso',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '6',
  //       romanNumber: 'VI',
  //       name: 'Libertador Gral. Bernardo O’Higgins',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '7',
  //       romanNumber: 'VII',
  //       name: 'Maule',
  //       countryID: 'CL'
  //     },

  //     {
  //       regionID: '8',
  //       romanNumber: 'VIII',
  //       name: 'Biobío',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '9',
  //       romanNumber: 'IX',
  //       name: 'Araucanía',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '10',
  //       romanNumber: 'X',
  //       name: 'Los Lagos',
  //       countryID: 'CL'
  //     },

  //     {
  //       regionID: '11',
  //       romanNumber: 'XI',
  //       name: 'Aysén del Gral. Carlos Ibáñez del Campo',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '12',
  //       romanNumber: 'XII',
  //       name: 'Magallanes y de la Antártica Chilena',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '13',
  //       romanNumber: 'XIII',
  //       name: 'Metropolitana de Santiago',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '14',
  //       romanNumber: 'XIV',
  //       name: 'Los Ríos',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '15',
  //       romanNumber: 'XV',
  //       name: 'Arica y Parinacota',
  //       countryID: 'CL'
  //     },
  //     {
  //       regionID: '16',
  //       romanNumber: 'XVI',
  //       name: 'Ñuble',
  //       countryID: 'CL'
  //     }

  //   ]
  // })

  // await prisma.communes.createMany({
  //   data: [
  //     { regionID: '15', name: 'Arica' },
  //     { regionID: '15', name: 'Camarones' },
  //     { regionID: '15', name: 'General Lagos' },
  //     { regionID: '15', name: 'Putre' },
  //     { regionID: '1', name: 'Alto Hospicio' },
  //     { regionID: '1', name: 'Camiña' },
  //     { regionID: '1', name: 'Colchane' },
  //     { regionID: '1', name: 'Huara' },
  //     { regionID: '1', name: 'Iquique' },
  //     { regionID: '1', name: 'Pica' },
  //     { regionID: '1', name: 'Pozo Almonte' },
  //     { regionID: '2', name: 'Antofagasta' },
  //     { regionID: '2', name: 'Calama' },
  //     { regionID: '2', name: 'María Elena' },
  //     { regionID: '2', name: 'Mejillones' },
  //     { regionID: '2', name: 'Ollagüe' },
  //     { regionID: '2', name: 'San Pedro de Atacama' },
  //     { regionID: '2', name: 'Sierra Gorda' },
  //     { regionID: '2', name: 'Taltal' },
  //     { regionID: '2', name: 'Tocopilla' },
  //     { regionID: '3', name: 'Alto del Carmen' },
  //     { regionID: '3', name: 'Caldera' },
  //     { regionID: '3', name: 'Chañaral' },
  //     { regionID: '3', name: 'Copiapó' },
  //     { regionID: '3', name: 'Diego de Almagro' },
  //     { regionID: '3', name: 'Freirina' },
  //     { regionID: '3', name: 'Huasco' },
  //     { regionID: '3', name: 'Tierra Amarilla' },
  //     { regionID: '3', name: 'Vallenar' },
  //     { regionID: '4', name: 'Andacollo' },
  //     { regionID: '4', name: 'Canela' },
  //     { regionID: '4', name: 'Combarbalá' },
  //     { regionID: '4', name: 'Coquimbo' },
  //     { regionID: '4', name: 'Illapel' },
  //     { regionID: '4', name: 'La Higuera' },
  //     { regionID: '4', name: 'La Serena' },
  //     { regionID: '4', name: 'Los Vilos' },
  //     { regionID: '4', name: 'Monte Patria' },
  //     { regionID: '4', name: 'Ovalle' },
  //     { regionID: '4', name: 'Paiguano' },
  //     { regionID: '4', name: 'Punitaqui' },
  //     { regionID: '4', name: 'Río Hurtado' },
  //     { regionID: '4', name: 'Salamanca' },
  //     { regionID: '4', name: 'Vicuña' },
  //     { regionID: '5', name: 'Algarrobo' },
  //     { regionID: '5', name: 'Cabildo' },
  //     { regionID: '5', name: 'Calera' },
  //     { regionID: '5', name: 'Calle Larga' },
  //     { regionID: '5', name: 'Cartagena' },
  //     { regionID: '5', name: 'Casablanca' },
  //     { regionID: '5', name: 'Catemu' },
  //     { regionID: '5', name: 'Concón' },
  //     { regionID: '5', name: 'El Quisco' },
  //     { regionID: '5', name: 'El Tabo' },
  //     { regionID: '5', name: 'Hijuelas' },
  //     { regionID: '5', name: 'Isla de Pascua' },
  //     { regionID: '5', name: 'Juan Fernández' },
  //     { regionID: '5', name: 'La Cruz' },
  //     { regionID: '5', name: 'La Ligua' },
  //     { regionID: '5', name: 'Limache' },
  //     { regionID: '5', name: 'Llaillay' },
  //     { regionID: '5', name: 'Los Andes' },
  //     { regionID: '5', name: 'Nogales' },
  //     { regionID: '5', name: 'Olmué' },
  //     { regionID: '5', name: 'Panquehue' },
  //     { regionID: '5', name: 'Papudo' },
  //     { regionID: '5', name: 'Petorca' },
  //     { regionID: '5', name: 'Puchuncaví' },
  //     { regionID: '5', name: 'Putaendo' },
  //     { regionID: '5', name: 'Quillota' },
  //     { regionID: '5', name: 'Quilpué' },
  //     { regionID: '5', name: 'Quintero' },
  //     { regionID: '5', name: 'Rinconada' },
  //     { regionID: '5', name: 'San Antonio' },
  //     { regionID: '5', name: 'San Esteban' },
  //     { regionID: '5', name: 'San Felipe' },
  //     { regionID: '5', name: 'Santa María' },
  //     { regionID: '5', name: 'Santo Domingo' },
  //     { regionID: '5', name: 'Valparaíso' },
  //     { regionID: '5', name: 'Villa Alemana' },
  //     { regionID: '5', name: 'Viña del Mar' },
  //     { regionID: '5', name: 'Zapallar' },
  //     { regionID: '13', name: 'Alhué' },
  //     { regionID: '13', name: 'Buin' },
  //     { regionID: '13', name: 'Calera de Tango' },
  //     { regionID: '13', name: 'Cerrillos' },
  //     { regionID: '13', name: 'Cerro Navia' },
  //     { regionID: '13', name: 'Colina' },
  //     { regionID: '13', name: 'Conchalí' },
  //     { regionID: '13', name: 'Curacaví' },
  //     { regionID: '13', name: 'El Bosque' },
  //     { regionID: '13', name: 'El Monte' },
  //     { regionID: '13', name: 'Estación Central' },
  //     { regionID: '13', name: 'Huechuraba' },
  //     { regionID: '13', name: 'Independencia' },
  //     { regionID: '13', name: 'Isla de Maipo' },
  //     { regionID: '13', name: 'La Cisterna' },
  //     { regionID: '13', name: 'La Florida' },
  //     { regionID: '13', name: 'La Granja' },
  //     { regionID: '13', name: 'La Pintana' },
  //     { regionID: '13', name: 'La Reina' },
  //     { regionID: '13', name: 'Lampa' },
  //     { regionID: '13', name: 'Las Condes' },
  //     { regionID: '13', name: 'Lo Barnechea' },
  //     { regionID: '13', name: 'Lo Espejo' },
  //     { regionID: '13', name: 'Lo Prado' },
  //     { regionID: '13', name: 'Macul' },
  //     { regionID: '13', name: 'Maipú' },
  //     { regionID: '13', name: 'María Pinto' },
  //     { regionID: '13', name: 'Melipilla' },
  //     { regionID: '13', name: 'Ñuñoa' },
  //     { regionID: '13', name: 'Padre Hurtado' },
  //     { regionID: '13', name: 'Paine' },
  //     { regionID: '13', name: 'Pedro Aguirre Cerda' },
  //     { regionID: '13', name: 'Peñaflor' },
  //     { regionID: '13', name: 'Peñalolén' },
  //     { regionID: '13', name: 'Pirque' },
  //     { regionID: '13', name: 'Providencia' },
  //     { regionID: '13', name: 'Pudahuel' },
  //     { regionID: '13', name: 'Puente Alto' },
  //     { regionID: '13', name: 'Quilicura' },
  //     { regionID: '13', name: 'Quinta Normal' },
  //     { regionID: '13', name: 'Recoleta' },
  //     { regionID: '13', name: 'Renca' },
  //     { regionID: '13', name: 'San Bernardo' },
  //     { regionID: '13', name: 'San Joaquín' },
  //     { regionID: '13', name: 'San José de Maipo' },
  //     { regionID: '13', name: 'San Miguel' },
  //     { regionID: '13', name: 'San Pedro' },
  //     { regionID: '13', name: 'San Ramón' },
  //     { regionID: '13', name: 'Santiago' },
  //     { regionID: '13', name: 'Talagante' },
  //     { regionID: '13', name: 'Tiltil' },
  //     { regionID: '13', name: 'Vitacura' },
  //     { regionID: '6', name: 'Chimbarongo' },
  //     { regionID: '6', name: 'Chépica' },
  //     { regionID: '6', name: 'Codegua' },
  //     { regionID: '6', name: 'Coltauco' },
  //     { regionID: '6', name: 'La Estrella' },
  //     { regionID: '6', name: 'Malloa' },
  //     { regionID: '6', name: 'Marchihue' },
  //     { regionID: '6', name: 'Nancagua' },
  //     { regionID: '6', name: 'Navidad' },
  //     { regionID: '6', name: 'Olivar' },
  //     { regionID: '6', name: 'Palmilla' },
  //     { regionID: '6', name: 'Paredones' },
  //     { regionID: '6', name: 'Peralillo' },
  //     { regionID: '6', name: 'Peumo' },
  //     { regionID: '6', name: 'Pichidegua' },
  //     { regionID: '6', name: 'Pichilemu' },
  //     { regionID: '6', name: 'Placilla' },
  //     { regionID: '6', name: 'Pumanque' },
  //     { regionID: '6', name: 'Quinta de Tilcoco' },
  //     { regionID: '6', name: 'Rancagua' },
  //     { regionID: '6', name: 'Rengo' },
  //     { regionID: '6', name: 'Requínoa' },
  //     { regionID: '6', name: 'San Fernando' },
  //     { regionID: '6', name: 'San Francisco de Mostazal' },
  //     { regionID: '6', name: 'San Vicente de Tagua Tagua' },
  //     { regionID: '6', name: 'Santa Cruz' },
  //     { regionID: '7', name: 'Cauquenes' },
  //     { regionID: '7', name: 'Chanco' },
  //     { regionID: '7', name: 'Colbún' },
  //     { regionID: '7', name: 'Constitución' },
  //     { regionID: '7', name: 'Curepto' },
  //     { regionID: '7', name: 'Curicó' },
  //     { regionID: '7', name: 'Empedrado' },
  //     { regionID: '7', name: 'Hualañé' },
  //     { regionID: '7', name: 'Licantén' },
  //     { regionID: '7', name: 'Linares' },
  //     { regionID: '7', name: 'Longaví' },
  //     { regionID: '7', name: 'Maule' },
  //     { regionID: '7', name: 'Molina' },
  //     { regionID: '7', name: 'Parral' },
  //     { regionID: '7', name: 'Pelarco' },
  //     { regionID: '7', name: 'Pelluhue' },
  //     { regionID: '7', name: 'Pencahue' },
  //     { regionID: '7', name: 'Rauco' },
  //     { regionID: '7', name: 'Retiro' },
  //     { regionID: '7', name: 'Romeral' },
  //     { regionID: '7', name: 'Río Claro' },
  //     { regionID: '7', name: 'Sagrada Familia' },
  //     { regionID: '7', name: 'San Clemente' },
  //     { regionID: '7', name: 'San Javier de Loncomilla' },
  //     { regionID: '7', name: 'San Rafael' },
  //     { regionID: '7', name: 'Talca' },
  //     { regionID: '7', name: 'Teno' },
  //     { regionID: '7', name: 'Vichuquén' },
  //     { regionID: '7', name: 'Villa Alegre' },
  //     { regionID: '7', name: 'Yerbas Buenas' },
  //     { regionID: '16', name: 'Bulnes' },
  //     { regionID: '16', name: 'Chillán Viejo' },
  //     { regionID: '16', name: 'Chillán' },
  //     { regionID: '16', name: 'Cobquecura' },
  //     { regionID: '16', name: 'Coelemu' },
  //     { regionID: '16', name: 'Coihueco' },
  //     { regionID: '16', name: 'El Carmen' },
  //     { regionID: '16', name: 'Ninhue' },
  //     { regionID: '16', name: 'Ñiquén' },
  //     { regionID: '16', name: 'Pemuco' },
  //     { regionID: '16', name: 'Pinto' },
  //     { regionID: '16', name: 'Portezuelo' },
  //     { regionID: '16', name: 'Quillón' },
  //     { regionID: '16', name: 'Quirihue' },
  //     { regionID: '16', name: 'Ránquil' },
  //     { regionID: '16', name: 'San Carlos' },
  //     { regionID: '16', name: 'San Fabián' },
  //     { regionID: '16', name: 'San Ignacio' },
  //     { regionID: '16', name: 'San Nicolás' },
  //     { regionID: '16', name: 'Treguaco' },
  //     { regionID: '16', name: 'Yungay' },
  //     { regionID: '8', name: 'Alto Biobío' },
  //     { regionID: '8', name: 'Antuco' },
  //     { regionID: '8', name: 'Arauco' },
  //     { regionID: '8', name: 'Cabrero' },
  //     { regionID: '8', name: 'Cañete' },
  //     { regionID: '8', name: 'Chiguayante' },
  //     { regionID: '8', name: 'Concepción' },
  //     { regionID: '8', name: 'Contulmo' },
  //     { regionID: '8', name: 'Coronel' },
  //     { regionID: '8', name: 'Curanilahue' },
  //     { regionID: '8', name: 'Florida' },
  //     { regionID: '8', name: 'Hualpén' },
  //     { regionID: '8', name: 'Hualqui' },
  //     { regionID: '8', name: 'Laja' },
  //     { regionID: '8', name: 'Lebu' },
  //     { regionID: '8', name: 'Los Álamos' },
  //     { regionID: '8', name: 'Los Ángeles' },
  //     { regionID: '8', name: 'Lota' },
  //     { regionID: '8', name: 'Mulchén' },
  //     { regionID: '8', name: 'Nacimiento' },
  //     { regionID: '8', name: 'Negrete' },
  //     { regionID: '8', name: 'Penco' },
  //     { regionID: '8', name: 'Quilaco' },
  //     { regionID: '8', name: 'Quilleco' },
  //     { regionID: '8', name: 'San Pedro de la Paz' },
  //     { regionID: '8', name: 'San Rosendo' },
  //     { regionID: '8', name: 'Santa Bárbara' },
  //     { regionID: '8', name: 'Santa Juana' },
  //     { regionID: '8', name: 'Talcahuano' },
  //     { regionID: '8', name: 'Tirúa' },
  //     { regionID: '8', name: 'Tomé' },
  //     { regionID: '8', name: 'Tucapel' },
  //     { regionID: '8', name: 'Yumbel' },
  //     { regionID: '9', name: 'Angol' },
  //     { regionID: '9', name: 'Carahue' },
  //     { regionID: '9', name: 'Cholchol' },
  //     { regionID: '9', name: 'Collipulli' },
  //     { regionID: '9', name: 'Cunco' },
  //     { regionID: '9', name: 'Curacautín' },
  //     { regionID: '9', name: 'Curarrehue' },
  //     { regionID: '9', name: 'Ercilla' },
  //     { regionID: '9', name: 'Freire' },
  //     { regionID: '9', name: 'Galvarino' },
  //     { regionID: '9', name: 'Gorbea' },
  //     { regionID: '9', name: 'Lautaro' },
  //     { regionID: '9', name: 'Loncoche' },
  //     { regionID: '9', name: 'Lonquimay' },
  //     { regionID: '9', name: 'Los Sauces' },
  //     { regionID: '9', name: 'Lumaco' },
  //     { regionID: '9', name: 'Melipeuco' },
  //     { regionID: '9', name: 'Nueva Imperial' },
  //     { regionID: '9', name: 'Padre las Casas' },
  //     { regionID: '9', name: 'Perquenco' },
  //     { regionID: '9', name: 'Pitrufquén' },
  //     { regionID: '9', name: 'Pucón' },
  //     { regionID: '9', name: 'Purén' },
  //     { regionID: '9', name: 'Renaico' },
  //     { regionID: '9', name: 'Saavedra' },
  //     { regionID: '9', name: 'Temuco' },
  //     { regionID: '9', name: 'Teodoro Schmidt' },
  //     { regionID: '9', name: 'Toltén' },
  //     { regionID: '9', name: 'Traiguén' },
  //     { regionID: '9', name: 'Victoria' },
  //     { regionID: '9', name: 'Vilcún' },
  //     { regionID: '9', name: 'Villarrica' },
  //     { regionID: '14', name: 'Corral' },
  //     { regionID: '14', name: 'Futrono' },
  //     { regionID: '14', name: 'La Unión' },
  //     { regionID: '14', name: 'Lago Ranco' },
  //     { regionID: '14', name: 'Lanco' },
  //     { regionID: '14', name: 'Los Lagos' },
  //     { regionID: '14', name: 'Máfil' },
  //     { regionID: '14', name: 'Mariquina' },
  //     { regionID: '14', name: 'Paillaco' },
  //     { regionID: '14', name: 'Panguipulli' },
  //     { regionID: '14', name: 'Río Bueno' },
  //     { regionID: '14', name: 'Valdivia' },
  //     { regionID: '10', name: 'Ancud' },
  //     { regionID: '10', name: 'Calbuco' },
  //     { regionID: '10', name: 'Castro' },
  //     { regionID: '10', name: 'Chaitén' },
  //     { regionID: '10', name: 'Chonchi' },
  //     { regionID: '10', name: 'Cochamó' },
  //     { regionID: '10', name: 'Curaco de Vélez' },
  //     { regionID: '10', name: 'Dalcahue' },
  //     { regionID: '10', name: 'Fresia' },
  //     { regionID: '10', name: 'Frutillar' },
  //     { regionID: '10', name: 'Futaleufú' },
  //     { regionID: '10', name: 'Hualaihué' },
  //     { regionID: '10', name: 'Llanquihue' },
  //     { regionID: '10', name: 'Los Muermos' },
  //     { regionID: '10', name: 'Maullín' },
  //     { regionID: '10', name: 'Osorno' },
  //     { regionID: '10', name: 'Palena' },
  //     { regionID: '10', name: 'Puerto Montt' },
  //     { regionID: '10', name: 'Puerto Octay' },
  //     { regionID: '10', name: 'Puerto Varas' },
  //     { regionID: '10', name: 'Puqueldón' },
  //     { regionID: '10', name: 'Purranque' },
  //     { regionID: '10', name: 'Puyehue' },
  //     { regionID: '10', name: 'Queilén' },
  //     { regionID: '10', name: 'Quellón' },
  //     { regionID: '10', name: 'Quemchi' },
  //     { regionID: '10', name: 'Quinchao' },
  //     { regionID: '10', name: 'Río Negro' },
  //     { regionID: '10', name: 'San Juan de la Costa' },
  //     { regionID: '10', name: 'San Pablo' },
  //     { regionID: '11', name: 'Aisén' },
  //     { regionID: '11', name: 'Chile Chico' },
  //     { regionID: '11', name: 'Cisnes' },
  //     { regionID: '11', name: 'Cochrane' },
  //     { regionID: '11', name: 'Coihaique' },
  //     { regionID: '11', name: 'Guaitecas' },
  //     { regionID: '11', name: 'Lago Verde' },
  //     { regionID: '11', name: 'O’Higgins' },
  //     { regionID: '11', name: 'Río Ibáñez' },
  //     { regionID: '11', name: 'Tortel' },
  //     { regionID: '12', name: 'Antártica' },
  //     { regionID: '12', name: 'Cabo de Hornos (Ex Navarino)' },
  //     { regionID: '12', name: 'Laguna Blanca' },
  //     { regionID: '12', name: 'Natales' },
  //     { regionID: '12', name: 'Porvenir' },
  //     { regionID: '12', name: 'Primavera' },
  //     { regionID: '12', name: 'Punta Arenas' },
  //     { regionID: '12', name: 'Río Verde' },
  //     { regionID: '12', name: 'San Gregorio' },
  //     { regionID: '12', name: 'Timaukel' },
  //     { regionID: '12', name: 'Torres del Paine' }
  //   ]
  // })
}

main()
  .then(async () => await prisma.$disconnect())
  .catch(async (error) => {
    console.error('Error:', error)
    await prisma.$disconnect()
    process.exit(1)
  })
